name: phantom
description: The torch of black flames continues to burn
version: 1.0.0
repository: https://github.com/ArcaneArts/phantom
environment:
  sdk: ^3.4.1
dependencies:
  shelf: ^1.4.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
