name: phantom
description: The torch of black flames continues to burn
version: 1.0.0
repository: https://github.com/ArcaneArts/phantom
environment:
  sdk: ^3.4.1
dependencies:
  shelf: ^1.4.1
  synchronized: ^3.1.0+1
  thread: ^0.2.2
  toxic: ^1.0.4
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
