name: phantom
description: The torch of black flames continues to burn
version: 1.0.0
repository: https://github.com/ArcaneArts/phantom
environment:
  sdk: ^3.4.1
dependencies:
  google_cloud: ^0.2.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  shelf: ^1.4.2
  synchronized: ^3.1.0+1
  thread: ^0.2.2
  http: ^1.2.1
  shelf_router: ^1.1.4
  shelf_multipart: ^1.0.0
  shelf_web_socket: ^2.0.0
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  toxic: ^1.0.4
  curse: ^1.0.3
  chat_color: ^1.0.0
  color: ^3.0.0
  precision_stopwatch: ^1.0.2
  watcher: ^1.1.0
  reflect_buddy: ^1.4.2
  hotreloader: ^4.2.0
  args: ^2.5.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
